# Use postgres/example user/password credentials
version: '3.1'

networks:
  postgres:
    driver: bridge

services:
  users_db:
    image: postgres
    env_file: .env.example
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-1q2w3e4r}
      PGDATA: /data/postgres
    volumes:
      - ./deploy/users_db:/data/postgres
    ports:
      - "${DB_PORT:-15432}:5432"
    networks:
      - postgres
    restart: unless-stopped